[app]
# 监听所有网络接口，允许外部访问
address = "0.0.0.0:9000"

# Database.
[db]
# 直接使用 Railway 提供的 PostgreSQL DSN
address = "postgresql://postgres:HXQFjrGICvdVZnnJFCZPGQkGMVzedqRz@maglev.proxy.rlwy.net:19628/railway?sslmode=disable"

# 其他数据库连接参数
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"

# 可选的 PostgreSQL 连接参数
params = ""
