[app]
# 监听所有网络接口，允许外部访问
address = "0.0.0.0:9000"

# Database.
[db]
host = "maglev.proxy.rlwy.net"
port = 19628
user = "postgres"
password = "HXQFjrGICvdVZnnJFCZPGQkGMVzedqRz"
database = "railway"
# 其他数据库连接参数
ssl_mode = "require"
max_open = 25
max_idle = 25
max_lifetime = "300s"

# 可选的 PostgreSQL 连接参数
params = ""
