[app]
# Listen on all interfaces
address = "0.0.0.0"
port = 8080

[db]
host = "${DB_HOST}"
port = "${DB_PORT}"
user = "${DB_USER}"
password = "${DB_PASSWORD}"

# Ensure that this database has been created in Postgres.
database = "${DB_NAME}"

ssl_mode = "require"
max_open = 25
max_idle = 25
max_lifetime = "300s"

# Optional space separated Postgres DSN params. eg: "application_name=listmonk gssencmode=disable"
params = ""
